server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.1.182:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: abc123
  application:
    name: service-provider  # 定义应用名称，注册到eureka的服务名称

mybatis:
  # 定义mybatis要扫描的包路径和对应的xml路径
  type-aliases-package: com.ylsoft.pojo
  mapper-locations: classpath:mappers/*.xml
eureka:
  client:
    service-url:  #EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    register-with-eureka: true # 默认就是true。启动服务后会自动向EurekaServer发起一个Rest请求，里面包含自己的元数据信息。