server:
  port: 10010
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:  #EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
zuul:
  routes:
    service-provider: /service-provider/** # 这里是映射路径
    service-clent: /service-clent/** # 这里是映射路径
  prefix: /api # 添加路由前缀
spring:
  application:
    name: api-gateway